# This script was generated by SVP 4 Manager.
# Check https://www.svp-team.com for more details.

import vapoursynth as vs
core = vs.core
core.num_threads = 9

if not hasattr(core,'svp1'):
    core.std.LoadPlugin("/nix/store/xxpj92wmrnjjx579mzcvpg3h008krbys-svp-dist-4.5.210-2/opt/plugins/libsvpflow1_vs64.so")
if not hasattr(core,'svp2'):
    core.std.LoadPlugin("/nix/store/xxpj92wmrnjjx579mzcvpg3h008krbys-svp-dist-4.5.210-2/opt/plugins/libsvpflow2_vs64.so")

clip = video_in

super_params     = "{pel:1,scale:{up:2},gpu:0,full:false,rc:true}"
analyse_params   = "{main:{search:{coarse:{distance:-8},type:2}}}"
smoothfps_params = "{rate:{num:2,den:1},algo:13,mask:{area:100},scene:{}}"

src_fps     = container_fps if container_fps>0.1 else 24
demo_mode   = 0
stereo_type = 0
nvof = 0

########## BEGIN OF base.py ##########
# This file is a part of SmoothVideo Project (SVP) ver.4
# This is NOT the full Vapoursynth script, all used variables are defined via
# JScript code that generates the full script text.

def interpolate(clip):
# input_um - original frame in 4:2:0
# input_m  - cropped and resized (if needed) frame
# input_m8 - input_m converted to 8-bit
    input_um = clip.resize.Point(format=vs.YUV420P8,dither_type="random")
    input_m = input_um
    input_m = input_m.std.CropRel(0,0,0,2)
    input_m8 = input_m

    if nvof:
        smooth  = core.svp2.SmoothFps_NVOF(input_m,smoothfps_params,nvof_src=input_m8,src=input_um,fps=src_fps)
    else:
        super   = core.svp1.Super(input_m8,super_params)
        vectors = core.svp1.Analyse(super["clip"],super["data"],input_m8,analyse_params)
        smooth  = core.svp2.SmoothFps(input_m,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=input_um,fps=src_fps)


    if demo_mode==1:
        return demo(input_m,smooth)
    else:
        return smooth

if stereo_type == 1:
    lf = interpolate(core.std.CropRel(clip,0,(int)(clip.width/2),0,0))
    rf = interpolate(core.std.CropRel(clip,(int)(clip.width/2),0,0,0))
    smooth = core.std.StackHorizontal([lf, rf])
elif stereo_type == 2:
    lf = interpolate(core.std.CropRel(clip,0,0,0,(int)(clip.height/2)))
    rf = interpolate(core.std.CropRel(clip,0,0,(int)(clip.height/2),0))
    smooth = core.std.StackVertical([lf, rf])
else:
    smooth =  interpolate(clip)
########### END OF base.py ###########


smooth.set_output()
